drop table USER  if exists;
CREATE TABLE USER  (
	ID BIGINT NOT NULL ,
	USER_ID VARCHAR(50) NOT NULL ,
	USER_NAME VARCHAR(50) NOT NULL
) ;
CREATE SEQUENCE user_seq START WITH 1 CACHE 1000;

drop table CARD  if exists;
CREATE TABLE CARD  (
	USER_ID BIGINT NOT NULL ,
	CARD_BALANCE BIGINT NOT NULL,
	CARD_ID BIGINT NOT NULL 
) ;
CREATE SEQUENCE user_card_seq START WITH 1 CACHE 1000;