CREATE TABLE user_details (
  username VARCHAR(50) NOT NULL PRIMARY KEY,
  email VARCHAR(50),
  password VARCHAR(500),
  activated VARCHAR(50),
  activationkey VARCHAR(50),
  resetpasswordkey VARCHAR(50)
);

CREATE TABLE authority (
  name VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE user_authority 
   (	username VARCHAR(50) NOT NULL,
	authority VARCHAR(50) NOT NULL
	
   );
alter table user_authority add CONSTRAINT FK_user FOREIGN KEY (username) REFERENCES user_details (username) ;
alter table user_authority add CONSTRAINT FK_authority FOREIGN KEY (authority) REFERENCES authority (name) ;
ALTER TABLE user_authority ADD CONSTRAINT Uniqque_authority_unique UNIQUE (username,authority);

CREATE TABLE oauth_access_token (
  token_id VARCHAR(256) DEFAULT NULL,
  token BLOB,
  authentication_id VARCHAR(256) DEFAULT NULL,
  user_name VARCHAR(256) DEFAULT NULL,
  client_id VARCHAR(256) DEFAULT NULL,
  authentication BLOB,
  refresh_token VARCHAR(256) DEFAULT NULL
);

CREATE TABLE oauth_refresh_token (
  token_id VARCHAR(256) DEFAULT NULL,
  token BLOB,
  authentication BLOB
);

  
CREATE TABLE ACCOUNT  (
	ID NUMBER(19,0) ,
	SORT_CODE NUMBER(19,0),
	 PRIMARY KEY (ID)
) ;
CREATE SEQUENCE account_info_seq START WITH 1 CACHE 1000;

CREATE TABLE TRANSACTION  (
	ID NUMBER(19,0) NOT NULL ENABLE, 
	BANK_TRAN_CODE VARCHAR2(255 CHAR), 
	BANK_TRAN_SUB_CODE VARCHAR2(255 CHAR), 
	BOOKED_DATE_TIME TIMESTAMP (6), 
	CREDIT_DEBIT_INDICATOR VARCHAR2(255 CHAR), 
	INTER_BOOKED_BAL_AMT FLOAT(126), 
	INTER_BOOKED_BAL_CURR_CODE VARCHAR2(255 CHAR), 
	INTER_BOOKED_CR_DB_IND VARCHAR2(255 CHAR), 
	MERCHANT_CATEGORY_CODE VARCHAR2(255 CHAR), 
	MERCHANT_NAME VARCHAR2(255 CHAR), 
	PERMANENT_ACCOUNT_NUMBER VARCHAR2(255 CHAR), 
	POSTED_DATE_TIME TIMESTAMP (6), 
	PROPRIETARY_TRAN_CODE VARCHAR2(255 CHAR), 
	PROPRIETARY_TRAN_ISSUER VARCHAR2(255 CHAR), 
	TRANSACTION_AMOUNT FLOAT(126), 
	TRANSACTION_CURR_CODE VARCHAR2(255 CHAR), 
	TRAN_DESCRIPTION VARCHAR2(255 CHAR), 
	TRANSACTION_STATUS VARCHAR2(255 CHAR), 
	TYPE VARCHAR2(255 CHAR), 
	ACCOUNT_ID NUMBER(19,0), 
	 PRIMARY KEY (ID),
  
	 CONSTRAINT FK60OGQ0GA4X4Y0FKEU24TGM0KV FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT (ID) 
) ;
CREATE SEQUENCE transaction_seq START WITH 1 CACHE 1000;